feat(drawzone): Gestion tactille
PsycleResearch/repsycle-front pull request #33
Opened 2022-06-15 14:23 UTC by mbaumanndev

Changements apportés :
- Gestion des événements tactilles dans la drawzone

2022-06-16 14:33 UTC, mbaumanndev commented on package.json
> +    "lodash": "^4.17.21"
useless

2022-06-16 15:25 UTC, Mindstan requested changes

2022-06-16 15:25 UTC, Mindstan commented on src/draw-zone/hooks.ts
> +            ;(this as unknown as LinkedHTMLElement).instance.fire('deselect')
C’est voulu le `;` en début de ligne ?

2022-06-16 15:25 UTC, Mindstan commented on src/draw-zone/hooks.ts
> +            point.scale(5 / 7)
Peut-être stocker quelque part `7/5` ou `5/7` en constante, vu que cette valeur est utilisée à 2 endrois

2022-06-17 06:59 UTC, mbaumanndev commented on src/draw-zone/hooks.ts
> +            ;(this as unknown as LinkedHTMLElement).instance.fire('deselect')
Oui, sans le `;` on a une erreur de syntaxe à cause de l'appel de fonction une ligne avant le cast

2022-06-17 09:36 UTC, Mindstan approved these changes
J'approuve pour pas que ce soit bloqué jusqu'à ce que je revienne.

2022-06-17 13:58 UTC, danousna requested changes

2022-06-17 14:01 UTC, mbaumanndev commented on src/draw-zone/hooks.ts
> +    function drawRect({
Oui, mais il est modifié pour gérer ce qu'il faut (2 points => 4 points)

2022-06-17 14:04 UTC, danousna approved these changes

2022-06-20 07:44 UTC, Mindstan approved these changes

2022-08-18 09:12 UTC, Mindstan approved these changes

2022-08-18 09:12 UTC, Mindstan commented on package.json
> +  "version": "0.0.27-beta.7",
c’est voulu le `.` ?

2022-08-18 09:17 UTC, mbaumanndev commented on package.json
> +  "version": "0.0.27-beta.7",
Oui, c'est pour mieux respecter le semver

2022-08-25 15:36 UTC, Mindstan approved these changes

2022-08-26 10:36 UTC, danousna approved these changes
très clean la modif DrawZone

2022-08-26 10:36 UTC, danousna commented on src/draw-zone/state.ts
> +export const DrawZone2Context = createContext<DrawZoneStateContext>({
pk drawzone2 ?

2022-08-26 15:29 UTC, mbaumanndev commented on src/draw-zone/state.ts
> +export const DrawZone2Context = createContext<DrawZoneStateContext>({
Un oubli, au début j'avais dupliqué le code pour avoir une référence et un WIP

2022-09-15 12:35 UTC, merged